trigger:
  - develop

pool: oelite-build-agents

steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'OElite Platform Azure Subscription(10136124-f099-450c-a694-41ac5b6560a8)'
      KeyVaultName: 'oelite-devops-cred'
      SecretsFilter: '*'
      RunAsPreJob: true

  - task: mirror-git-repository-vsts-task@1
    displayName: 'Mirror code to Github'
    inputs:
      sourceGitRepositoryUri: '$(Build.Repository.Uri)'
      sourceGitRepositoryPersonalAccessToken: '$(lida-devops-token)'
      destinationGitRepositoryUri: 'https://github.com/oelite/RESTme.Dapper.git'
      destinationGitRepositoryPersonalAccessToken: '$(lida-github-token)'

  - task: UseDotNet@2
    inputs:
      version: '6.x'
      packageType: sdk

  - task: CmdLine@2
    displayName: 'Restore Nuget Packages'
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'

  - task: CmdLine@2
    displayName: 'Pack Nuget Packages'
    inputs:
      script: |
        dotnet pack OElite.Restme.Dapper.Common/OElite.Restme.Dapper.Common.csproj -o $(Build.ArtifactStagingDirectory)/oelite-pack -c Release --version-suffix ci$(Build.BuildId)
        dotnet pack OElite.Restme.Dapper/OElite.Restme.Dapper.csproj -o $(Build.ArtifactStagingDirectory)/oelite-pack -c Release --version-suffix ci$(Build.BuildId)

  - task: NuGetCommand@2
    displayName: 'Push Nuget Packages'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'e89aaa35-ebc6-4df0-a763-4a5f58ef878f'

